### ISSUE TITLE
lol .... I worked on a planning poker app too 

### ISSUE THREAD

**Issue by luciotudisco** [tibordp/planning-poker#21]
pokersizing.com !

Sorry I read your recent blog post when you posted it on Linked then stumbled into your gtithub repo and found it funny that you worked on a planning poker app too!

**Comment by tibordp** [comment]
hehe, nice! yeah, sth like this was sorely needed for our use as the ones we used previously flaked out really often and were not very nice in general. we host this one internally and it's working quite well.
